# Generated by Django 5.0.7 on 2024-07-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию продукта', max_length=100, verbose_name='категория')),
                ('description', models.TextField(blank=True, help_text='Введите описание категории продукта', null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите наименование продукта', max_length=100, verbose_name='наименование')),
                ('description', models.CharField(help_text='Введите описание продукта', max_length=100, verbose_name='описание')),
                ('image', models.ImageField(blank=True, help_text='загрузите изображение продукта', null=True, upload_to='catalog/image', verbose_name='изображение')),
                ('date_create', models.DateField(blank=True, help_text='Укажите дату создания записи в БД', null=True, verbose_name='дата создания')),
                ('date_change', models.DateField(blank=True, help_text='Укажите дату изменения записи в БД', null=True, verbose_name='дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, help_text='введите категорию продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category', 'name'],
            },
        ),
    ]
