# Generated by Django 5.0.7 on 2024-07-30 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="date_change",
        ),
        migrations.RemoveField(
            model_name="product",
            name="date_create",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Укажите дату создания записи в БД",
                verbose_name="дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Укажите дату изменения записи в БД",
                verbose_name="дата последнего изменения",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Введите описание продукта",
                max_length=100,
                verbose_name="описание",
            ),
        ),
    ]
