# Generated by Django 5.0.7 on 2024-07-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="date_change",
        ),
        migrations.RemoveField(
            model_name="product",
            name="date_create",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату создания записи в БД",
                null=True,
                verbose_name="дата создания",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True,
                help_text="введите дату производства продукта",
                null=True,
                verbose_name="дата производства продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату изменения записи в БД",
                null=True,
                verbose_name="дата последнего изменения",
            ),
        ),
    ]
