# Generated by Django 5.0.7 on 2024-07-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_date_change_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
