# Generated by Django 5.0.7 on 2024-08-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={"verbose_name": "Версия", "verbose_name_plural": "Версии"},
        ),
    ]
